/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminAlertPopup: typeof import('./components/admin/AlertPopup.vue')['default']
    AdminEditor: typeof import('./components/admin/Editor.vue')['default']
    HomepageContent: typeof import('./components/homepage/Content.vue')['default']
    HomepageLightModeButton: typeof import('./components/homepage/LightModeButton.vue')['default']
    HomepageMainSection: typeof import('./components/homepage/MainSection.vue')['default']
    HomepageMessageBoard: typeof import('./components/homepage/MessageBoard.vue')['default']
    HomepageNavbar: typeof import('./components/homepage/Navbar.vue')['default']
    HomepageSvgMoonIcon: typeof import('./components/homepage/svg/moonIcon.vue')['default']
    HomepageSvgSunIcon: typeof import('./components/homepage/svg/sunIcon.vue')['default']
    Mybutton: typeof import('./components/Mybutton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Test: typeof import('./components/Test.vue')['default']
  }
}
